library(music)
# 
# buildChord("C4", chord = "major", play = T, plot = T,formatNotation = TRUE)
# 
# mbuildChord("F4", chord = "major", play = T, plot = T,formatNotation = TRUE)
# 
# buildChord("G4", chord = "major", play = T, plot = T,formatNotation = TRUE)
# 
# buildChord("C4", chord = "major", play = T, plot = T,formatNotation = TRUE)
# 
# buildScale("C4",scale = "major",descending=F,play=T)

bpm <- 0.4

playNote("E4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("A4",oscillator = "saw",duration = 3)
Sys.sleep(bpm*4)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("A4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 2)
Sys.sleep(bpm*3)
playNote("G4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E4",oscillator = "saw",duration = 2)
Sys.sleep(bpm*3)

playNote("E4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("A4",oscillator = "saw",duration = 3)
Sys.sleep(bpm*4)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("A4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 2)
Sys.sleep(bpm*3)
playNote("G4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E4",oscillator = "saw",duration = 2)
Sys.sleep(bpm*5)

playNote("C3",oscillator = "square",duration = 4)
playNote("C3",oscillator = "saw",duration = 4)
Sys.sleep(bpm*5)
playNote("B2",oscillator = "square",duration = 4)
playNote("B2",oscillator = "saw",duration = 4)
Sys.sleep(bpm*5)
playNote("A2",oscillator = "square",duration = 1)
playNote("A2",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
# playNote("G2",oscillator = "square",duration = 1)
# playNote("G2",oscillator = "saw",duration = 1)
# Sys.sleep(bpm)
playNote("G2",oscillator = "square",duration = 3)
playNote("G2",oscillator = "saw",duration = 3)
Sys.sleep(bpm*4)
playNote("E2",oscillator = "square",duration = 3)
playNote("E2",oscillator = "saw",duration = 3)
Sys.sleep(bpm*4)

playNote("C3",oscillator = "square",duration = 4)
playNote("C3",oscillator = "saw",duration = 4)
Sys.sleep(bpm*5)
playNote("B2",oscillator = "square",duration = 4)
playNote("B2",oscillator = "saw",duration = 4)
Sys.sleep(bpm*5)
playNote("E3",oscillator = "square",duration = 3)
playNote("E4",oscillator = "saw",duration = 3)
Sys.sleep(bpm*4)
playNote("G#3",oscillator = "square",duration = 2)
playNote("G#4",oscillator = "saw",duration = 2)
Sys.sleep(bpm*2)
playNote("A3",oscillator = "square",duration = 1)
playNote("A4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B3",oscillator = "square",duration = 1)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm*3)

playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("A4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("F5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("G4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 2)
Sys.sleep(bpm*2)
playNote("D5",oscillator = "saw",duration = 2)
Sys.sleep(bpm*2)

playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("A4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("F5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("G4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 3)
Sys.sleep(bpm*3)
# playNote("D5",oscillator = "saw",duration = 2)
# Sys.sleep(bpm*2)

playNote("G5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("A4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("F5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("G4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 2)
Sys.sleep(bpm*2)
playNote("D5",oscillator = "saw",duration = 2)
Sys.sleep(bpm*2)

playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("A4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("F5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("G4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E5",oscillator = "saw",duration = 3)
Sys.sleep(bpm*3)
# playNote("D5",oscillator = "saw",duration = 2)
# Sys.sleep(bpm*2)

playNote("E4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("A4",oscillator = "saw",duration = 3)
Sys.sleep(bpm*4)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("A4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 2)
Sys.sleep(bpm*3)
playNote("G4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E4",oscillator = "saw",duration = 2)
Sys.sleep(bpm*3)

playNote("E4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("A4",oscillator = "saw",duration = 3)
Sys.sleep(bpm*4)
playNote("C5",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("A4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("B4",oscillator = "saw",duration = 2)
Sys.sleep(bpm*3)
playNote("G4",oscillator = "saw",duration = 1)
Sys.sleep(bpm)
playNote("E4",oscillator = "saw",duration = 2)
Sys.sleep(bpm*5)